apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker-tdcfuture
spec:
  host: tdcfuture-service.default.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 2
      consecutiveGatewayErrors: 1
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 100

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tdcfuture-vs
spec:
  hosts: 
  - tdcfuture-service
  http:
    - route:
      - destination:
          host: tdcfuture-service
          subset: v1
        weight: 50
      - destination:
          host: tdcfuture-service
          subset: v2
        weight: 50
