apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdcfuture
  labels:
    app: tdcfuture
spec:
  selector:
    matchLabels:
      app: tdcfuture    
  replicas: 2
  template:
    metadata:
      labels:
        app: "tdcfuture"
    spec:
      containers:
        - name: tdcfuture
          image: "danielrodriguess/tdcfuture-2022:latest"
          resources:
            requests: 
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 80m
              memory: 128Mi

          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 4
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 15