apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tdcfuture-vs
spec:
  hosts: 
  - tdcfuture-service.default.svc.cluster.local
  http:
    - fault:
        delay:
          fixedDelay: 10s
          percentage:
            value: 50
        abort:
          httpStatus: 504
          percentage:
            value: 10
      route:  
      - destination:
          host: tdcfuture-service
          subset: all

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tdcfuture-dr
spec:
  host: tdcfuture-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "x-user"
  subsets:
    - name: all
      labels:
        app: nginx