apiVersion: v1
kind: Service
metadata:
  name: tdcfuture-service
spec:
  selector:
    app: tdcfuture
  type: ClusterIP
  ports:
  - name: tdcfuture-service
    port: 80
    targetPort: 3000
    protocol: TCP